### ISSUE TITLE
parabam importing rules

### ISSUE THREAD

**Issue by JenniferShelton** [jhrf/parabam#1]
Let me amend that. I see the docs use the name 'engine' rather than 'rule' for the function. I have it running now. Thanks

Hi, parabam reports an error when passed the name of a rule file in my working directory. Any suggestions?

```
parabam subset \
> --rule get_unmapped_reads \
> --input $bam
```

traceback:
```
[Error] parabam stopped unexpecedtly, sorry!
Traceback (most recent call last):
  File "parabam/core.pyx", line 49, in parabam.core.CmdLineInterface.handle (parabam/core.c:2960)
  File "parabam/command/subset.pyx", line 187, in parabam.command.subset.Subset.run_cmd (parabam/command/subset.c:7191)
  File "parabam/command/core.pyx", line 395, in parabam.command.core.Interface.__get_module_and_vitals__ (parabam/command/core.c:10079)
AttributeError: 'module' object has no attribute 'rule'
```

Best:)

**Comment by jhrf** [comment]
Hi Jennifer,

Thanks so much for using parabam.

It looks like your instruction file doesn't have a "rule" function. This is
likely because the docs are hideously outdated and specify that you should
have an "engine" function. Simply change the name of your engine function
to "rule" and it should work. If that doesn't work send me your instruction
file and I'll correct it.

I am a PHD student writing up my thesis so time is really short. But I
really want to get around to making the user interface and docs more up to
date. You sending me this email is a good kick up the butt.

Thanks

Henry

**Comment by jhrf** [comment]
I updated the docs to read "rule" rather than "engine" (which is deprecated). Glad you got it working.
